### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by medallyon** [Medallyon/exambot#4]
## Internal Systems
- [x] Modular Structure
- [x] Create dynamic modular structure
- [ ] User Permission System
## Command Modules
- [x] Ping
- [x] Eval
- [x] Help
- [ ] WhoIs
- [ ] Wikipedia
- [ ] YouTube Searching & Streaming
## Web Panel
- [x] Homepage
- [ ] Features Page
- [ ] User Login
- [ ] Server List
- [ ] Server Dashboard
- [ ] User Profiles
- [ ] Wiki
